[tool.poetry]
name = "lfs-testing-demo"
version = "0.1.0"
description = "Toy app to demonstrate test techniques for Learning Futures Studio associates."
authors = ["Jim Pfleger <jim.pfleger@verizon.com>"]
readme = "README.md"
packages = [{include = "lfs_testing_demo"}]

[tool.poetry.dependencies]
python = "^3.11"
transitions = "^0.9.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
